# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---

- name: generate ca key
  shell:
    cmd: "curl -OOOOOOOOO https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/multiregion/{README.md,client-secure.yaml,cluster-init-secure.yaml,cockroachdb-statefulset-secure.yaml,dns-lb.yaml,example-app-secure.yaml,external-name-svc.yaml,setup.py,teardown.py}"
    chdir: cockroach/files
    creates: cockroach/files/setup.py

- name: Copy clean version of setup.py to use location
  copy:
    src: cockroach/files/setup.py
    dest: cockroach/files/setup.py.clean

- name: Copy clean version to use location
  copy:
    src: cockroach/files/teardown.py
    dest: cockroach/files/teardown.py.clean
