# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---
- name: add python prereqs
  include_tasks: add-python.yml
  when:
    - add_python|bool

- name: clean certs directory
  include_tasks: clean-cert.yml

- name: get necessary cockroach files
  include_tasks: get-cockroach.yml
  when:
    - get_cockroach|bool

# will not use both of these and hopefully neither and can use original.  
# top one replaces setup whereas the second one patches the original setup
- name: replace out setup.py
  include_tasks: replace-setup.yml
  when:
    - replace_setup|bool

- name: patch setup.py
  include_tasks: patch-setup.yml
  when:
    - patch_setup|bool

- name: edit setup.py
  include_tasks: edit-setup.yml
  when:
    - edit_setup|bool

- name: edit teardown.py
  include_tasks: edit-teardown.yml
  when:
    - edit_teardown|bool

- name: edit cockroachdb-statefulset-secure.yaml
  include_tasks: edit-stateful.yml
  when:
    - edit_stateful|bool

- name: run setup.py
  shell: 
    cmd: "{{ ansible_venv }}/bin/python setup.py"
    chdir: cockroach/files 
  when:
    - run_setup|bool
