- name: deploy cockroach yaml
  kubernetes.core.k8s:
    state: present
    namespace: "{{ cockroach_namespace }}"
    kubeconfig: "{{ KUBECONFIG }}"
    src: cockroachdb-statefulset.yaml

- name: wait until cockroach pod is running
  shell:
    cmd: "kubectl -n {{ cockroach_namespace }} get pod/cockroachdb-0 |grep cockroachdb-0 | grep Running"
  register: running_output
  retries: 20
  until: running_output.stdout | length > 0

- name: wait 2  seconds
  pause:
    seconds: 2

- name: init cockroach db
  kubernetes.core.k8s_exec:
    namespace: "{{ cockroach_namespace }}"
    pod: cockroachdb-0
    command: /cockroach/cockroach init --certs-dir=/cockroach/cockroach-certs
    kubeconfig: "{{ KUBECONFIG }}"
  ignore_errors: yes
