- name: Apply CockroachDB StatefulSet
  shell: kubectl apply -n {{ cockroach_namespace }} -f cockroach/files/cockroachdb-statefulset.yaml
  environment:
    KUBECONFIG: "{{ KUBECONFIG }}"
  register: kubectl_output

- name: Show kubectl apply output
  debug:
    var: kubectl_output.stdout

- name: wait until cockroach pod is running
  shell:
    cmd: "kubectl -n {{ cockroach_namespace }} get pod/cockroachdb-0 |grep cockroachdb-0 | grep Running"
  register: running_output
  retries: 20
  until: running_output.stdout | length > 0

- name: wait 2  seconds
  pause:
    seconds: 2

- name: Initialize CockroachDB
  shell: >
    kubectl exec -n {{ cockroach_namespace }} cockroachdb-0 -- 
    /cockroach/cockroach init --certs-dir=/cockroach/cockroach-certs
  environment:
    KUBECONFIG: "{{ KUBECONFIG }}"
  ignore_errors: yes

